### PR TITLE
Plotting Updates

### PR DESCRIPTION
**Pull request by samuel-marsh**
Hi Phillip,

Here is another PR with some updates to several aspects.  Feel free to ignore or use whatever you like.

In my comments on previous PR this morning I thought I had found the error in `distGenes` with labels but actually still having issues.  I'll open issue with that though because I'm not sure what's going on.

**plotting.R:**
- Fixed typos
- Removed return plot param on `DistPlot` to match all other plots which just explicitly return the ggplot2 object.
- Some styling to make easier code reading (or at least to me)
- Add roxygen skeleton for `FDRDistPlot` and `plotBetas` so that they have manual pages and show up in package help documentation.
    - NOTE: I left the description of these functions with "ADD DESCRIPTION HERE" as I wanted to leave it you you/team as to how you want to describe those functions
- Added code link in parameter for `scd.object`.  This way the manual page has clickable link to `scDist` function.
- Removed code `library(ggplot2)` placed outside of functions.
- Removed code creating sample dataset outside of functions.
- Moved ggplot2 and ggrepel imports to specific functions instead of global.
    - This also removes the need for `ggplot2::` and `ggrepel::` in function code so removed that as well.

**scDist.R**
- Added check for format of `normalized_counts` and internally convert to matrix as needed with `as.matrix`.
- Added check for presence of rownames in`normalized_counts` prior to transposing.  Ensures `out$gene.names` is appropriately recorded.
    - Currently function will run but there won't be a slot of `gene.names` in the output if rownames are absent.
- Added explicit imports of irlba, lmerTest, lme4, and ashr for `scDist` function (removing `::`).
    - Adds these packages to NAMESPACE.
    - Also added ashr to Description file to ensure user packages are checked during package installation.

**zzz.R**
- Updated info to precent error in roxygen with deprecation of doctype.

Again, please feel free to use or ignore any of this, they're just some quick extra thoughts after running scDist couple more times this AM.
Thanks again!
Sam

### CODE REVIEW

**Comment by samuel-marsh** [comment]
Just added two additional potential changes.
- Added parameter `num_genes` to `distGenes` plot to give user control of number of genes colored/labeled.
- Added 3 color parameters to `FDRDistPlot` to give users control of colors used in the plot.

Best,
Sam

**Comment by phillipnicol** [comment]
Thank you! I have merged this into `dev` and will look this over, and will also add documentation for those functions (as well as an example on how to use them in the demo). I can't remember if the `scDist` function works for `sparseMatrix`; if so, then we would only want to convert to matrix if it is not either of those types. Thanks again for these improvements, I really appreciate it!

**Comment by samuel-marsh** [comment]
Hi Phillip,

No problem, happy to help!  There are two issues with sparse matrices in my testing.  First, is that base R `t()` doesn't work on sparse matrices so you need `Matrix::t()`.  This isn't huge issue and most people have Matrix installed already but it does become somewhat limiting when installing from CRAN as Matrix requires >=4.4.0.

The bigger issue is time.  In my testing on matrix that is 33441 genes x 39103 cells and has 13 clusters.
- Running with dense matrix (performing the dense conversion before starting the function) (input matrix size 10.5GB).
    - It took ~5.5 minutes and needed a total of 48GB of RAM.
 - Running with dgCMatrix (modifying function to use `Matrix::t()`) (input matrix size 1.1GB).
     - It took ~61.5 minutes and needed a total of 37GB of RAM.
 So it was 10x slower and didn't actually save that much memory in long run (probably step in function that also does a dense conversion?).

It's possible that reaplcing the `for` loop with parallelize function (using `future_lapply` or `foreach` or something else) could result in faster times for sparse matrices.  But given the memory benefit is relatively low that's probably not too worthwhile unless memory usage can be altered too.

Best,
Sam

**Comment by phillipnicol** [comment]
Hi Sam, 

Thanks again for the help! I have just integrated these changes into the main package. 

Also thank you for checking on the performance of `scDist` with a sparse matrix input. I think that the PCA step of centering genes will likely cause the matrix to lose sparsity. It might be possible to find a workaround but I would have to think carefully...

It also seems like the memory usage could be improved by only making the conversion to dense matrix after subsetting to a particular cell type. Let me know if this is something that would be useful for you, but it already seems to be running decently on your large example with 30,000+ genes and cells.

**Pull request merged**
